name: Quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^2.1.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  string_stats: ^0.0.3
  flutter_staggered_grid_view: ^0.4.1
  share: ^2.0.4
  lottie: ^1.2.1
  flutter_native_splash: ^2.2.16
  badges: ^3.0.2
  emoji_picker_flutter: ^1.5.2
  camera: ^0.9.4+5
  image_picker: ^0.8.4+4
  image_cropper: ^3.0.1
  path_provider: ^2.0.13
  path:
  shared_preferences: ^2.0.15
  video_player: ^1.0.1
  socket_io_client: ^0.9.12
  flutter_keyboard_visibility: ^5.4.0
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_messaging: ^14.2.5
  firebase_in_app_messaging: ^0.7.0+14
  uni_links: ^0.5.1
  permission_handler: ^10.2.0
  sentry_flutter: ^6.20.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
 

 

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  image: images/logo.png
  android_disable_fullscreen: true



 
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/logo.png
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Hacen
      fonts:
        - asset: fonts/Hacen-Liner-Print-out.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  