// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt60yKGnODFCdqz3TtuzJ1RiV5ig7AtQ4',
    appId: '1:234265645190:web:b227f94c1225d9533a8107',
    messagingSenderId: '234265645190',
    projectId: 'quran-7e2f3',
    authDomain: 'quran-7e2f3.firebaseapp.com',
    storageBucket: 'quran-7e2f3.appspot.com',
    measurementId: 'G-YT9KYRWNZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkRGTX2gjcS4WVviUvnArTkmKs8ke_Ko',
    appId: '1:234265645190:android:ffad419d4282d0933a8107',
    messagingSenderId: '234265645190',
    projectId: 'quran-7e2f3',
    storageBucket: 'quran-7e2f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRT8YMgLUVd_-hr82VlYptNkZjGvG-sZI',
    appId: '1:234265645190:ios:5c690eb0125bfecb3a8107',
    messagingSenderId: '234265645190',
    projectId: 'quran-7e2f3',
    storageBucket: 'quran-7e2f3.appspot.com',
    iosClientId: '234265645190-k52u6a6tvdrn58bd7jt3avhieb9ltvkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranTry',
  );
}
